# Generated by Django 5.1 on 2024-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_water_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='daily_goal',
            field=models.IntegerField(default=0),
        ),
    ]
